name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - publish

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Dependencies
        run: |
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact for Deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2